services:
    db:
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: 123VN123vn*
            MYSQL_DATABASE: chatbot
            MYSQL_USER: appuser
            MYSQL_PASSWORD: 123BD123bd*
        volumes:
            - db_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5
    backend:
        build: ./be-chat-bot
        ports:
            - "3000:3000"
        environment:
            DB_HOST: db
            DB_USER: appuser
            DB_PASSWORD: 123BD123bd*
            DB_NAME: chatbot
        depends_on:
            db:
                condition: service_healthy

    frontend:
        build: ./fe-chat-bot
        ports:
            - "8080:80"
        depends_on:
            - backend

volumes:
    db_data:
