services:
    db:
        image: mysql:8
        command: --mysql-native-password=1
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        image: redis:7
        ports:
            - "6379:6379"

    backend:
        build: ./be-chat-bot
        ports:
            - "3000:3000"
        volumes:
            - ./be-chat-bot:/app
            - /app/node_modules
        env_file:
            - .env # đọc từ root .env
        environment:
            DATABASE_URL: ${DATABASE_URL}
            DB_HOST: db
            DB_PORT: 3306
            DB_USER: ${MYSQL_USER}
            DB_PASS: ${MYSQL_PASSWORD}
            DB_NAME: ${MYSQL_DATABASE}
            REDIS_URL: redis://redis:6379
            JWT_SECRET: ${JWT_SECRET}
            ACCESS_TOKEN_TTL: 900
            REFRESH_TOKEN_TTL: 604800
            PASSWORD_TOKEN_TTL: 1800
            PASSWORD_SECRET: ${PASSWORD_SECRET}
            NODE_ENV: development
            AI_MODEL: nvidia/nemotron-3-super-120b-a12b:free
            AI_OPENROUTER_API_KEY: ${AI_OPENROUTER_API_KEY}
            CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
            CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
            CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
            MAIL_AUTH_USER: ${MAIL_AUTH_USER}
            MAIL_AUTH_PASS: ${MAIL_AUTH_PASS}
            EMAIL_SECRET: ${EMAIL_SECRET}
            EMAIL_TOKEN_TTL: 3600
            EMAIL_FROM: ${EMAIL_FROM}
            EMAIL_TO: ${EMAIL_TO}
            SYSTEM_PROMPT: "Bạn là trợ lý AI hỗ trợ lập trình viên. Trả lời bằng tiếng Việt."
            VITE_SECRET_RECAPTCHA: ${VITE_SECRET_RECAPTCHA}
        depends_on:
            db:
                condition: service_healthy
            redis:
                condition: service_started

    frontend:
        build: ./fe-chat-bot
        ports:
            - "8080:80"
        volumes:
            - ./fe-chat-bot:/app
            - /app/node_modules
        environment:
            CHOKIDAR_USEPOLLING: true
        depends_on:
            - backend

    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - frontend
            - backend

volumes:
    db_data:
